# Bookmarks Plugin
# https://github.com/dedukun/bookmarks.yazi

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"


# max-preview.yazi Plugin
# https://github.com/yazi-rs/plugins/tree/main/max-preview.yazi
[[manager.prepend_keymap]]
on   = "i"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"


# Smart-enter plugin
# See https://github.com/Ape/smart-enter.yazi
[[manager.prepend_keymap]]
on   = "l"
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"
