# For reference, see
# - https://yazi-rs.github.io/docs/configuration/yazi
# - https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi.toml


[manager]
ratio = [ 1, 3, 4 ]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = false

[opener]
open_image = [
    { run = 'feh -Zr "$@"', desc = "Open Image" },
]

[open]
prepend_rules = [
  { mime = "image/*", use = [ "open_image", "open" ] }
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
