#
# yazi.toml
# Yazi configuration.
#
# Yazi merges its default configuration in
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
# with this file.
#
#     [open] → Routing
#   [opener] → Command
#
# To change how a file is opened, add a prepend rule so that we can control the routing
#

[mgr]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = false

[opener]
open_html = [
    { run = 'open %s', desc = "Open in browser", for = "macos" },
    { run = 'xdg-open %s1', desc = "Open in browser", for = "linux" },
]

open_image = [
    { run = 'feh -Zr "$@"', desc = "Open Image" },
]

play = [
  { run = "xdg-open %s1", orphan = true, desc = "Play" },
]

tag = [
    { run = 'easytag "$@"', orphan = true, desc = 'Tag' }
]

[open]
prepend_rules = [
  { url = "*.{htm,html}", use = [ "open_html" ] },
  { url = "*.md", use = [ "edit", "open", "reveal" ] },
  { url = "*.markdown", use = [ "edit", "open", "reveal" ] },
  { mime = 'audio/*', use = [ 'play', 'tag', 'reveal' ] },
]

append_rules = [
  { mime = "image/*", use = [ "open_image", "open" ] }
]

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
